version: '3'

services:
  refine-with-newtype-postgres:
    container_name: refied-with-newtype
    image: postgres:10.7
    ports:
      - "9999:5432"
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --locale=C"
    volumes:
      - ./postgresql/init:/docker-entrypoint-initdb.d
